### PR TITLE
Added kill-session alias

### PR DESCRIPTION
**Pull request by martinbee**
Call tmk and then tmux session name to kill that session.

### CODE REVIEW

**Comment by martinbee** [comment]
I thought this looked cut and dry, but apparently I know nothing about aliases

**Comment by martinbee** [comment]
From what I can see, tmux.zsh is brought into .stack.d setting the aliases there? If not, close this pull request and please point me in the right direction.

Have a great weekend!

**Comment by osxi** [comment]
Cool-- I always though you had to include the parameters in the alias like `tmux kill-session -t $1` where `$1` is the name of the session.

**Comment by MatthewHager** [comment]
Just tested this and it works. Thanks!

**Pull request merged**
